---
- name: Install dependencies.
  become: true
  package:
    name: 
      - p7zip
      - xorriso
    state: present

- name: Install StormSSH for managaing ssh config.
  pip:
    name: 
      - setuptools
      - stormssh

- name: Make temporary directory for installation.
  file: 
    path: "{{ install_dir }}"
    state: directory



