---
- name: Make ssh key to login.
  openssh_keypair:
    path: "{{ ssh_keyfile }}"
    type: ed25519
    size: 2048
    state: present
    force: no
  register: ssh_data


- set_fact:
    ssh_public_key: "{{ ssh_data.public_key }}"


- name: Delete previous SSH configs.
  community.general.ssh_config:
    ssh_config_file: "/home/{{ username }}/.ssh/config"
    host: "{{ server_ip }}"
    state: absent

- name: Modify known_hosts so it doesn't have data from older connections.
  known_hosts:
    name: "{{ server_ip }}"
    path: "/home/{{ username }}/.ssh/known_hosts"
    state: absent

- name: Make SSH config for easier login in future.
  community.general.ssh_config:
    user: "{{ username }}" 
    host: "{{ hostname }}"
    hostname: "{{ server_ip }}"
    identity_file: "{{ ssh_keyfile_public }}"
    port: "{{ ssh_port }}" ## Note this is using non-default port that is only configured in different playbook. This won't work after installation. 
    state: present
